package com.donglan.chrona.data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** Removes only identical drafts and preserves overlapping independent appointments. */
public final class CandidateRules {
    private CandidateRules() { }

    public static List<EventCandidate> apply(List<EventCandidate> candidates) {
        ArrayList<EventCandidate> result = new ArrayList<>();
        for (EventCandidate candidate : candidates) {
            boolean duplicate = false;
            for (EventCandidate existing : result) {
                if (same(existing, candidate)) { duplicate = true; break; }
            }
            if (!duplicate) result.add(candidate);
        }
        boolean[] conflict = new boolean[result.size()];
        for (int i = 0; i < result.size(); i++) {
            EventCandidate left = result.get(i);
            if (!appointment(left)) continue;
            for (int j = i + 1; j < result.size(); j++) {
                EventCandidate right = result.get(j);
                if (appointment(right) && left.startAtMillis < right.endAtMillis
                        && right.startAtMillis < left.endAtMillis) conflict[i] = conflict[j] = true;
            }
        }
        for (int i = 0; i < result.size(); i++) {
            EventCandidate value = result.get(i);
            if (conflict[i] && value.uncertaintyLevel != EventCandidate.DOUBTFUL) result.set(i, new EventCandidate(
                    value.id, value.taskId, value.title, value.startAtMillis, value.endAtMillis,
                    value.timeZoneId, value.location, value.description, value.reminderMinutesBefore,
                    true, value.calendarEventId, value.category, value.allDay, value.endAutoGenerated,
                    EventCandidate.DOUBTFUL));
        }
        return result;
    }

    private static boolean appointment(EventCandidate value) {
        return EventCategory.EVENT.equals(value.category) && !value.allDay
                && value.startAtMillis != null && value.endAtMillis != null
                && value.endAtMillis > value.startAtMillis;
    }

    private static boolean same(EventCandidate a, EventCandidate b) {
        return a.taskId == b.taskId && Objects.equals(a.title, b.title)
                && Objects.equals(a.startAtMillis, b.startAtMillis) && Objects.equals(a.endAtMillis, b.endAtMillis)
                && Objects.equals(a.timeZoneId, b.timeZoneId) && Objects.equals(a.location, b.location)
                && Objects.equals(a.description, b.description)
                && Objects.equals(a.reminderMinutesBefore, b.reminderMinutesBefore)
                && a.needsConfirmation == b.needsConfirmation && a.allDay == b.allDay
                && a.uncertaintyLevel == b.uncertaintyLevel
                && a.endAutoGenerated == b.endAutoGenerated
                && Objects.equals(a.category, b.category) && Objects.equals(a.calendarEventId, b.calendarEventId);
    }
}
