package com.donglan.chrona.data;

import java.util.*;

/** Exact business identity; nullable values and provenance flags remain significant. */
public final class DuplicateCandidates {
    private DuplicateCandidates() { }
    public static List<Object> key(EventCandidate value) {
        return Arrays.asList(value.title, value.startAtMillis, value.endAtMillis,
                value.timeZoneId, value.location, value.description, value.category,
                value.allDay, value.reminderMinutesBefore, value.needsConfirmation,
                value.uncertaintyLevel, value.endAutoGenerated, value.calendarEventId);
    }
    public static List<List<EventCandidate>> groups(List<EventCandidate> candidates) {
        Map<List<Object>, List<EventCandidate>> groups = new LinkedHashMap<>();
        for (EventCandidate candidate : candidates)
            groups.computeIfAbsent(key(candidate), ignored -> new ArrayList<>()).add(candidate);
        List<List<EventCandidate>> result = new ArrayList<>();
        for (List<EventCandidate> group : groups.values()) if (group.size() > 1) result.add(group);
        return result;
    }
}
