package com.donglan.chrona.sync;

import com.donglan.chrona.data.EventCandidate;
import com.donglan.chrona.data.EventCategory;
import com.donglan.chrona.timetable.AcademicTerms;
import com.donglan.chrona.timetable.Timetable;
import com.donglan.chrona.timetable.TimetableParser;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/** Portable content only: credentials, calendar IDs, reminder settings and paths never cross devices. */
public final class TaskCodec {
    public static final long MAX_ATTACHMENT_BYTES = 20L * 1024 * 1024;
    public static final int MAX_TASK_BYTES = 8 * 1024 * 1024;
    private static final long MIN_TIME = -62_135_596_800_000L, MAX_TIME = 253_402_300_799_999L;

    private TaskCodec() { }

    public static JSONObject candidate(EventCandidate value) throws IOException {
        try {
            return new JSONObject().put("id", UUID.randomUUID().toString())
                    .put("title", value.title).put("startAt", nullable(value.startAtMillis))
                    .put("endAt", nullable(value.endAtMillis)).put("zone", text(value.timeZoneId, "UTC"))
                    .put("location", text(value.location, "")).put("description", text(value.description, ""))
                    .put("category", value.category).put("allDay", value.allDay)
                    .put("endAutoGenerated", value.endAutoGenerated).put("uncertainty", value.uncertaintyLevel);
        } catch (Exception exception) { throw invalid(exception); }
    }

    public static EventCandidate event(JSONObject value) throws IOException {
        try {
            checkCandidate(value);
            int uncertainty = value.getInt("uncertainty");
            return new EventCandidate(0, 0, value.getString("title"), millis(value, "startAt"),
                    millis(value, "endAt"), value.getString("zone"), value.getString("location"),
                    value.getString("description"), null, uncertainty != 0, null,
                    value.getString("category"), value.getBoolean("allDay"),
                    value.getBoolean("endAutoGenerated"), uncertainty);
        } catch (Exception exception) { throw invalid(exception); }
    }

    public static JSONObject validate(JSONObject source) throws IOException {
        try {
            if (source == null || source.toString().getBytes(StandardCharsets.UTF_8).length > MAX_TASK_BYTES)
                throw new IOException("单条同步记录过大");
            JSONObject value = new JSONObject(source.toString());
            String kind = value.getString("kind");
            if ("task".equals(kind)) {
                only(value, "kind", "rawText", "source", "createdAt", "status", "linkText", "candidates", "attachments");
                string(value, "rawText", 1_000_000, false);
                string(value, "source", 200, false);
                string(value, "linkText", 200_000, false);
                long created = integer(value, "createdAt");
                if (created < MIN_TIME || created > MAX_TIME) throw new IOException("记录时间无效");
                String status = value.getString("status");
                if (!java.util.Arrays.asList("ready", "needs_review", "failed").contains(status))
                    throw new IOException("不支持的同步记录状态");
                JSONArray candidates = value.getJSONArray("candidates");
                if (candidates.length() > 2000) throw new IOException("单条记录的日程数量过多");
                Set<String> ids = new HashSet<>();
                for (int i = 0; i < candidates.length(); i++) {
                    JSONObject candidate = candidates.getJSONObject(i);
                    checkCandidate(candidate);
                    if (!ids.add(candidate.getString("id"))) throw new IOException("日程身份重复");
                }
                JSONArray attachments = value.getJSONArray("attachments");
                if (attachments.length() > 64) throw new IOException("单条记录最多同步 64 个附件");
                for (int i = 0; i < attachments.length(); i++) {
                    JSONObject file = attachments.getJSONObject(i);
                    only(file, "sha", "name", "mime", "size", "image");
                    if (!file.getString("sha").matches("[0-9a-f]{64}")) throw new IOException("附件校验值无效");
                    string(file, "name", 255, true); string(file, "mime", 120, true);
                    long size = integer(file, "size");
                    if (size < 0 || size > MAX_ATTACHMENT_BYTES) throw new IOException("单个同步附件不能超过 20 MB");
                    bool(file, "image");
                    if (file.getBoolean("image") && !"image/jpeg".equals(file.getString("mime")))
                        throw new IOException("同步图片需要使用 JPEG 格式");
                }
            } else if ("term".equals(kind)) {
                only(value, "kind", "index", "document");
                term(value);
            } else throw new IOException("不支持的同步内容类型");
            return value;
        } catch (Exception exception) { throw invalid(exception); }
    }

    public static void validateId(String id, JSONObject payload) throws IOException {
        try {
            if ("task".equals(payload.getString("kind"))) {
                if (!id.matches("task_[0-9a-fA-F-]{36}")) throw new IOException("任务身份无效");
                UUID.fromString(id.substring(5));
            } else {
                JSONObject plan = payload.getJSONObject("document").getJSONObject("plan");
                int mode = plan.getInt("mode"), index = payload.getInt("index");
                int season = (mode < 2 ? mode * 2 : mode - 2) + index;
                if (!id.equals("term_" + plan.getInt("year") + "_" + season))
                    throw new IOException("学期身份与内容不一致");
            }
        } catch (Exception exception) { throw invalid(exception); }
    }

    public static final class Term {
        public final Timetable table;
        public final AcademicTerms.Plan plan;
        public final int index;
        public final java.util.Map<String, Boolean> classification;
        Term(Timetable table, AcademicTerms.Plan plan, int index, java.util.Map<String, Boolean> classification) {
            this.table = table; this.plan = plan; this.index = index; this.classification = classification;
        }
        public AcademicTerms.View view() {
            return new AcademicTerms.View(plan.entries(table, index), table.zone, classification);
        }
    }

    public static Term term(JSONObject payload) throws IOException {
        try {
            JSONObject document = payload.getJSONObject("document");
            only(document, "format", "name", "ics", "importedAt", "zone", "plan", "enabled", "classification");
            if (integer(document, "format") != 1) throw new IOException("课表格式不受支持");
            string(document, "name", 160, true);
            String source = string(document, "ics", TimetableParser.MAX_BYTES, true);
            ZoneId zone = ZoneId.of(document.getString("zone"));
            long imported = integer(document, "importedAt");
            if (imported < MIN_TIME || imported > MAX_TIME) throw new IOException("课表导入时间无效");
            JSONObject p = document.getJSONObject("plan");
            only(p, "year", "mode", "start", "split", "end");
            AcademicTerms.Plan plan = new AcademicTerms.Plan(Math.toIntExact(integer(p, "year")),
                    Math.toIntExact(integer(p, "mode")), LocalDate.parse(p.getString("start")),
                    LocalDate.parse(p.getString("split")), LocalDate.parse(p.getString("end")));
            int index = Math.toIntExact(integer(payload, "index"));
            if (index < 0 || index >= plan.count()) throw new IOException("学期编号无效");
            JSONArray enabled = document.getJSONArray("enabled");
            if (enabled.length() != 1 || !(enabled.get(0) instanceof Number) || enabled.getInt(0) != index)
                throw new IOException("同步课表必须只包含一个启用学期");
            Timetable table = TimetableParser.parse(source, zone);
            plan.validateCoverage(table);
            JSONObject choices = document.getJSONObject("classification");
            if (choices.length() > 30_000) throw new IOException("课表分类项过多");
            java.util.Map<String, Boolean> classification = new java.util.HashMap<>();
            java.util.Iterator<String> keys = choices.keys();
            while (keys.hasNext()) {
                String key = keys.next();
                if (key.length() > 2000 || !(choices.get(key) instanceof Boolean))
                    throw new IOException("课表分类项无效");
                classification.put(key, choices.getBoolean(key));
            }
            return new Term(table, plan, index, classification);
        } catch (Exception exception) { throw invalid(exception); }
    }

    private static void checkCandidate(JSONObject value) throws Exception {
        only(value, "id", "title", "startAt", "endAt", "zone", "location", "description", "category",
                "allDay", "endAutoGenerated", "uncertainty");
        UUID.fromString(string(value, "id", 36, true));
        string(value, "title", 4000, true); string(value, "location", 4000, false);
        string(value, "description", 200_000, false);
        ZoneId.of(value.getString("zone"));
        String category = value.getString("category");
        if (!java.util.Arrays.asList(EventCategory.VALUES).contains(category)) throw new IOException("日程类型无效");
        Long start = millis(value, "startAt"), end = millis(value, "endAt");
        if (start != null && end != null && end < start) throw new IOException("结束时间早于开始时间");
        bool(value, "allDay"); bool(value, "endAutoGenerated");
        long level = integer(value, "uncertainty");
        if (level < 0 || level > 2) throw new IOException("日程确认状态无效");
        if (value.getBoolean("allDay")) {
            if (start != null && Math.floorMod(start, 86_400_000L) != 0
                    || end != null && Math.floorMod(end, 86_400_000L) != 0)
                throw new IOException("全天日程必须使用 UTC 日期边界");
        }
    }

    private static Long millis(JSONObject value, String key) throws Exception {
        if (!value.has(key)) throw new IOException("同步记录缺少时间字段");
        if (value.isNull(key)) return null;
        long millis = integer(value, key);
        if (millis < MIN_TIME || millis > MAX_TIME) throw new IOException("日程时间无效");
        return millis;
    }
    private static long integer(JSONObject value, String key) throws Exception {
        Object item = value.get(key);
        if (!(item instanceof Number) || !item.toString().matches("-?(0|[1-9][0-9]*)"))
            throw new IOException("同步记录整数格式无效");
        return Long.parseLong(item.toString());
    }
    private static void bool(JSONObject value, String key) throws Exception {
        if (!(value.get(key) instanceof Boolean)) throw new IOException("同步记录开关格式无效");
    }
    private static String string(JSONObject value, String key, int maximum, boolean required) throws Exception {
        Object raw = value.get(key);
        if (!(raw instanceof String)) throw new IOException("同步记录文本格式无效");
        String result = (String) raw;
        if (result.length() > maximum || required && result.trim().isEmpty() || result.indexOf('\0') >= 0)
            throw new IOException("同步记录文本长度或内容无效");
        return result;
    }
    private static void only(JSONObject value, String... fields) throws IOException {
        Set<String> allowed = new HashSet<>(java.util.Arrays.asList(fields));
        java.util.Iterator<String> keys = value.keys();
        while (keys.hasNext()) if (!allowed.contains(keys.next())) throw new IOException("同步记录包含不支持的字段");
    }
    private static Object nullable(Object value) { return value == null ? JSONObject.NULL : value; }
    private static String text(String value, String fallback) { return value == null || value.isEmpty() ? fallback : value; }
    private static IOException invalid(Exception exception) {
        return exception instanceof IOException ? (IOException) exception : new IOException("同步记录格式无效", exception);
    }
}
