package com.donglan.chrona.ai;

import com.donglan.chrona.calendar.AllDayDates;
import com.donglan.chrona.data.EventCandidate;
import com.donglan.chrona.data.EventCategory;
import com.donglan.chrona.data.EventTimeDefaults;

import org.json.JSONException;
import org.json.JSONObject;

import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.util.List;

/** Converts extracted time facts into calendar values without guessing missing clock times. */
public final class SemanticEventNormalizer {
    private static final long MINUTE = 60_000L;
    // The editor displays four-digit Gregorian years; reject epoch values outside that domain.
    private static final long MIN_EPOCH = -62_135_596_800_000L;
    private static final long MAX_EPOCH = 253_402_300_799_999L;
    private static final DateTimeFormatter DUE_TEXT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    private SemanticEventNormalizer() { }

    private static final class Context {
        boolean uncertain;
        ZoneId zone;
        ZonedDateTime anchor;
    }

    private static final class TimeValue {
        LocalDate date;
        Long millis;
    }

    public static EventCandidate fromJson(long taskId, JSONObject event, long nowMillis,
            String fallbackZone) throws JSONException {
        Object rawTitle = event.opt("title");
        if (!(rawTitle instanceof String) || ((String) rawTitle).trim().isEmpty())
            throw new JSONException("Event title must be a nonempty string");
        String title = ((String) rawTitle).trim();
        Context context = new Context();
        Object confirmation = event.opt("needs_confirmation");
        context.uncertain = !(confirmation instanceof Boolean) || (Boolean) confirmation;
        String category = text(event, "category", context);
        if (category == null || !category.equals(EventCategory.normalize(category))) context.uncertain = true;
        category = EventCategory.normalize(category);
        String requestedZone = text(event, "time_zone_id", context);
        String zoneName = requestedZone == null ? fallbackZone : requestedZone;
        try {
            context.zone = ZoneId.of(zoneName);
            context.anchor = Instant.ofEpochMilli(nowMillis).atZone(context.zone);
        } catch (RuntimeException invalidZone) {
            context.uncertain = true;
        }
        boolean allDay = bool(event, "all_day", false, context);
        Long duration = integer(event, "duration_minutes", context);
        boolean invalidDuration = !event.isNull("duration_minutes") && (duration == null || duration <= 0);
        if (invalidDuration) context.uncertain = true;
        Long rawReminder = integer(event, "reminder_minutes_before", context);
        Integer reminder = null;
        if (rawReminder != null) {
            if (rawReminder < 0 || rawReminder > Integer.MAX_VALUE) context.uncertain = true;
            else reminder = rawReminder.intValue();
        }
        // The legacy protocol did not distinguish absent reminder from explicit no reminder.
        boolean specified = event.has("reminder_specified")
                ? bool(event, "reminder_specified", true, context) : rawReminder != null;
        boolean legacy = !event.has("start") && !event.has("end") && !event.has("due")
                && (event.has("start_at_millis") || event.has("end_at_millis"));
        Long start = null, end = null, due = null;
        boolean endAutoGenerated = false;
        if (context.zone != null) {
            if (legacy) {
                start = epoch(integer(event, "start_at_millis", context), context);
                end = epoch(integer(event, "end_at_millis", context), context);
                if (EventCategory.DEADLINE.equals(category)) due = end != null ? end : start;
            } else {
                TimeValue first = resolve(event, "start", context, null, allDay);
                TimeValue last = resolve(event, "end", context, first.date, allDay);
                TimeValue deadline = resolve(event, "due", context, null, allDay);
                if (!event.isNull("due")) {
                    category = EventCategory.DEADLINE;
                    if (allDay) {
                        if (deadline.date != null) {
                            if (first.date != null && !first.date.equals(deadline.date)) context.uncertain = true;
                            first.date = deadline.date;
                            last.date = deadline.date;
                        }
                    } else {
                        due = deadline.millis;
                        if (due != null && last.millis != null && !due.equals(last.millis)) context.uncertain = true;
                    }
                }
                if (allDay) {
                    try {
                        if (first.date != null) start = AllDayDates.utcStart(first.date.toString());
                        LocalDate inclusiveEnd = last.date == null ? first.date : last.date;
                        if (inclusiveEnd != null) end = AllDayDates.utcExclusiveEnd(inclusiveEnd.toString());
                    } catch (RuntimeException invalidDate) { context.uncertain = true; }
                } else {
                    start = first.millis;
                    end = due != null ? due : last.millis;
                }
            }
            if (!allDay) {
                if (duration != null && !invalidDuration && start != null && end != null
                        && end - start != durationMillis(duration, category, context)) context.uncertain = true;
                if (EventCategory.DEADLINE.equals(category)) {
                    if (due == null && (legacy || event.isNull("due"))) due = end != null ? end : start;
                    if (due != null) {
                        end = due;
                        if (invalidDuration) { start = null; context.uncertain = true; }
                        else if (start == null || start.equals(due)) start = add(due,
                                -durationMillis(duration, category, context), context);
                        else if (duration != null && due - start != durationMillis(duration, category, context))
                            context.uncertain = true;
                    }
                } else if (start != null && end == null && event.isNull("end") && !invalidDuration) {
                    end = add(start, durationMillis(duration, category, context), context);
                    endAutoGenerated = duration == null;
                } else if (legacy && start != null && end == null && !invalidDuration) {
                    end = add(start, durationMillis(duration, category, context), context);
                    endAutoGenerated = duration == null;
                }
            }
        }
        start = epoch(start, context);
        end = epoch(end, context);
        if (start != null && end != null && end <= start) {
            // Preserve the valid start for editing; never invent an overnight rollover.
            end = null;
            context.uncertain = true;
        }
        if (allDay && ((start != null && start % 86_400_000L != 0)
                || (end != null && end % 86_400_000L != 0))) {
            start = null;
            end = null;
            context.uncertain = true;
        }
        if (start == null || end == null) context.uncertain = true;
        if (EventCategory.DEADLINE.equals(category) && due != null && context.zone != null) {
            String formatted = Instant.ofEpochMilli(due).atZone(context.zone).format(DUE_TEXT);
            if (!title.contains(formatted)) title += "（截止 " + formatted + "）";
            if (!specified && rawReminder == null) reminder = deadlineReminder(due, nowMillis, context.zone);
        }
        return new EventCandidate(0, taskId, title, start, end,
                allDay ? "UTC" : context.zone == null ? null : context.zone.getId(),
                text(event, "location", context), text(event, "description", context), reminder,
                context.uncertain, null, category, allDay, endAutoGenerated && end != null);
    }

    private static TimeValue resolve(JSONObject event, String key, Context context,
            LocalDate inheritedDate, boolean allDay) {
        TimeValue result = new TimeValue();
        if (event.isNull(key)) return result;
        Object raw = event.opt(key);
        if (!(raw instanceof JSONObject)) { context.uncertain = true; return result; }
        JSONObject value = (JSONObject) raw;
        try {
            String explicitDate = text(value, "date", context);
            String clock = text(value, "time", context);
            Long day = integer(value, "day_offset", context);
            Long minutes = integer(value, "offset_minutes", context);
            Long weekday = integer(value, "weekday", context);
            Long week = integer(value, "week_offset", context);
            LocalDate relativeDate = day == null ? null : context.anchor.toLocalDate().plusDays(day);
            LocalDate weekdayDate = null;
            if (weekday != null) {
                if (weekday < 1 || weekday > 7) throw new IllegalArgumentException("Invalid weekday");
                weekdayDate = week == null
                        ? context.anchor.toLocalDate().with(TemporalAdjusters.nextOrSame(DayOfWeek.of(weekday.intValue())))
                        : context.anchor.toLocalDate().with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY))
                                .plusWeeks(week).plusDays(weekday - 1);
            } else if (week != null) context.uncertain = true;
            if (explicitDate != null) {
                if (!explicitDate.matches("\\d{4}-\\d{2}-\\d{2}")) throw new IllegalArgumentException("Invalid date");
                result.date = LocalDate.parse(explicitDate);
                if (relativeDate != null && !result.date.equals(relativeDate)) context.uncertain = true;
                if (weekday != null && result.date.getDayOfWeek().getValue() != weekday) context.uncertain = true;
                if (weekdayDate != null && week != null && !result.date.equals(weekdayDate)) context.uncertain = true;
            } else {
                result.date = relativeDate != null ? relativeDate : weekdayDate != null ? weekdayDate
                        : clock != null ? inheritedDate : null;
                if (relativeDate != null && weekdayDate != null && !relativeDate.equals(weekdayDate)) context.uncertain = true;
            }
            Long offsetInstant = minutes == null ? null : add(context.anchor.toInstant().toEpochMilli(),
                    Math.multiplyExact(minutes, MINUTE), context);
            if (offsetInstant != null && result.date == null && clock == null) {
                result.millis = offsetInstant;
                result.date = Instant.ofEpochMilli(offsetInstant).atZone(context.zone).toLocalDate();
                if (allDay) context.uncertain = true;
                return result;
            }
            if (allDay) {
                if (clock != null || minutes != null) context.uncertain = true;
                return result;
            }
            if (clock == null || result.date == null) { context.uncertain = true; return result; }
            if (!clock.matches("\\d{2}:\\d{2}(:\\d{2})?")) throw new IllegalArgumentException("Invalid clock");
            LocalDateTime local = result.date.atTime(LocalTime.parse(clock));
            if (explicitDate == null && day == null && weekday != null && week == null
                    && local.isBefore(context.anchor.toLocalDateTime())) {
                result.date = result.date.plusWeeks(1);
                local = result.date.atTime(LocalTime.parse(clock));
            }
            List<ZoneOffset> offsets = context.zone.getRules().getValidOffsets(local);
            if (offsets.size() != 1) { context.uncertain = true; return result; }
            result.millis = epoch(local.toInstant(offsets.get(0)).toEpochMilli(), context);
            if (offsetInstant != null && !offsetInstant.equals(result.millis)) context.uncertain = true;
        } catch (RuntimeException invalidTime) { context.uncertain = true; result.millis = null; result.date = null; }
        return result;
    }

    private static long durationMillis(Long duration, String category, Context context) {
        if (duration == null) return EventTimeDefaults.durationMillis(category);
        try {
            if (duration <= 0) throw new IllegalArgumentException("Invalid duration");
            return Math.multiplyExact(duration, MINUTE);
        } catch (RuntimeException invalid) { context.uncertain = true; return 0; }
    }

    private static Long add(long value, long delta, Context context) {
        try { return epoch(Math.addExact(value, delta), context); }
        catch (ArithmeticException overflow) { context.uncertain = true; return null; }
    }

    private static Long epoch(Long value, Context context) {
        if (value != null && (value < MIN_EPOCH || value > MAX_EPOCH)) {
            context.uncertain = true;
            return null;
        }
        return value;
    }

    private static int deadlineReminder(long due, long now, ZoneId zone) {
        if (due <= now || due - now <= 60 * MINUTE) return 10;
        if (Instant.ofEpochMilli(due).atZone(zone).toLocalDate()
                .equals(Instant.ofEpochMilli(now).atZone(zone).toLocalDate())) return 30;
        return due - now <= 3 * 24 * 60 * MINUTE ? 120 : 360;
    }

    private static String text(JSONObject object, String key, Context context) {
        if (object.isNull(key)) return null;
        Object value = object.opt(key);
        if (!(value instanceof String)) { context.uncertain = true; return null; }
        return ((String) value).trim().isEmpty() ? null : ((String) value).trim();
    }

    private static Long integer(JSONObject object, String key, Context context) {
        if (object.isNull(key)) return null;
        Object value = object.opt(key);
        if (!(value instanceof Integer) && !(value instanceof Long)) { context.uncertain = true; return null; }
        return ((Number) value).longValue();
    }

    private static boolean bool(JSONObject object, String key, boolean fallback, Context context) {
        if (!object.has(key)) return fallback;
        Object value = object.opt(key);
        if (!(value instanceof Boolean)) { context.uncertain = true; return fallback; }
        return (Boolean) value;
    }
}
