plugins {
    id 'com.android.application'
}

android {
    namespace 'com.donglan.chrona'
    compileSdk 36

    defaultConfig {
        applicationId 'com.donglan.chrona'
        minSdk 26
        targetSdk 36
        versionCode 10
        versionName '0.7.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
