package com.donglan.chrona;

import com.donglan.chrona.data.EventCandidate;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/** Complete saved-row identity retained beside an unsaved editor draft. */
final class CandidateEditBaseline {
    private CandidateEditBaseline() { }
    static String of(EventCandidate candidate) {
        if (candidate == null) return "";
        StringBuilder value = new StringBuilder();
        for (Object field : new Object[]{candidate.id, candidate.taskId, candidate.title,
                candidate.startAtMillis, candidate.endAtMillis, candidate.timeZoneId,
                candidate.location, candidate.description, candidate.reminderMinutesBefore,
                candidate.needsConfirmation, candidate.uncertaintyLevel, candidate.calendarEventId,
                candidate.category, candidate.allDay, candidate.endAutoGenerated}) {
            if (field == null) value.append("-1:");
            else { String text = field.toString(); value.append(text.length()).append(':').append(text); }
        }
        try {
            byte[] digest = MessageDigest.getInstance("SHA-256").digest(value.toString().getBytes(StandardCharsets.UTF_8));
            StringBuilder result = new StringBuilder();
            for (byte item : digest) result.append(String.format(java.util.Locale.ROOT, "%02x", item & 255));
            return result.toString();
        } catch (NoSuchAlgorithmException impossible) { throw new AssertionError(impossible); }
    }
    static void require(EventCandidate current, String expected) {
        if (expected == null || expected.isEmpty() || !of(current).equals(expected))
            throw new IllegalStateException("日程已在其他页面更新，请返回重新打开记录后再编辑；当前草稿已保留");
    }
}
