package com.donglan.chrona;

import com.donglan.chrona.data.EventCandidate;
import com.donglan.chrona.data.EventCategory;
import com.donglan.chrona.data.EventTimeDefaults;

public final class CandidateFeedbackCheck {
    public static void main(String[] args) {
        check(CandidateFeedback.state(false, false).contains("待确认"), "pending candidate");
        check(CandidateFeedback.state(true, false).equals("已写入日历"), "published candidate");
        check(CandidateFeedback.state(true, true).contains("修改待保存"), "published draft edits");
        check(!CandidateFeedback.saveFailure(true).contains("待确认"), "update failure retains published meaning");
        check(CandidateFeedback.saveFailure(false).contains("尚未写入"), "insert failure");
        check(CandidateFeedback.timeHint("", "", false, false).contains("开始与结束"), "missing both");
        check(CandidateFeedback.timeHint("", "end", false, false).contains("开始"), "missing start");
        check(CandidateFeedback.timeHint("start", "", true, false).contains("补充结束"), "missing end takes priority");
        check(CandidateFeedback.timeHint("start", "end", true, false).contains("默认"), "default end");
        check(CandidateFeedback.timeHint("start", "end", false, false).isEmpty(), "manual end clears hint");
        check(CandidateFeedback.timeHint("start", "end", true, true).isEmpty(), "all day does not promise timed default");
        EventCandidate regular = EventTimeDefaults.completeInterval(candidate(100L, null, EventCategory.EVENT));
        check(regular.endAutoGenerated, "regular lone start receives default end");
        check(CandidateFeedback.automaticEnd(null, false, false), "new ordinary time retains automatic completion");
        check(!CandidateFeedback.automaticEnd(3600100L, false, false), "explicit end remains manual");
        EventCandidate explicit = EventTimeDefaults.completeInterval(candidate(100L, 3600100L, EventCategory.EVENT));
        check(!explicit.endAutoGenerated, "explicit one-hour end is not default");
        for (EventCandidate deadline : new EventCandidate[]{candidate(100000L, null, EventCategory.DEADLINE),
                candidate(null, 100000L, EventCategory.DEADLINE)}) {
            EventCandidate completed = EventTimeDefaults.completeInterval(deadline);
            check(completed.endAtMillis == 100000L && !completed.endAutoGenerated,
                    "explicit deadline survives interval completion without default-end hint");
            check(!CandidateFeedback.automaticEnd(deadline.endAtMillis, completed.endAutoGenerated, true),
                    "editor does not overwrite an explicit deadline when its start changes");
        }
        CategoryTimeChange due = CategoryTimeChange.from(EventCategory.EVENT, EventCategory.DEADLINE,
                100000L, 3700000L, true, false);
        check(due.start == 40000L && due.end == 100000L && !due.automaticEnd,
                "switch to deadline derives start and freezes the explicit due time");
        check(CandidateFeedback.timeHint("start", "end", due.automaticEnd, false).isEmpty(),
                "deadline conversion never claims its due time was defaulted");
        check(CategoryTimeChange.from(EventCategory.EVENT, EventCategory.TASK,
                100000L, 3700000L, false, false) == null, "explicit ends survive category changes");
        check(CategoryTimeChange.from(EventCategory.EVENT, EventCategory.TASK,
                100000L, 3700000L, true, true) == null, "all-day dates survive category changes");
        check(CategoryTimeChange.from(EventCategory.EVENT, EventCategory.TASK,
                100000L, 3700000L, true, false).end == 1900000L, "generated end follows category duration");
        System.out.println("CandidateFeedbackCheck passed: publication, failures, missing times, defaults and explicit deadlines");
    }
    private static EventCandidate candidate(Long start, Long end, String category) {
        return new EventCandidate(1, 1, "test", start, end, "UTC", "", "", null,
                true, null, category, false, false);
    }
    private static void check(boolean value, String label) {
        if (!value) throw new AssertionError(label);
    }
}
