/* Browser interaction check against clearly labelled mock phone data. No Android claims. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('./lan_browser_cdp.cjs');
const root=path.resolve(__dirname,'../app/src/main/assets/lan'),out=path.resolve(__dirname,'../build/lan-web-checks');
fs.mkdirSync(out,{recursive:true});
const source=http.createServer((req,res)=>{const file={'/':'index.html','/app.js':'app.js','/style.css':'style.css'}[req.url];if(!file){res.writeHead(404);res.end();return;}res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,file)));});
let paired=false,revision=1,nextId=2;
const tasks=[{id:1,text:'明天下午三点图书馆学习\n<script>unsafe()</script>',linkText:'链接正文 <b>保持原文</b>',status:'needs_review',error:'',created:1791072000000,source:'浏览器检查 · 模拟手机数据'}];
const candidate={id:11,taskId:1,title:'图书馆学习',start:1791072000000,end:1791075600000,zone:'Asia/Shanghai',location:'图书馆',description:'核对日程',category:'event',allDay:false,reminder:10,needsConfirmation:true,calendarLinked:false};
let candidates=[candidate],selected='2026-autumn';
const mutations=[],errors=[];
async function mock(route){const request=route.request(),url=new URL(request.url()),body=request.postDataJSON();let status=200,data={};
 if(url.pathname==='/api/pair'){paired=body.code==='000007';if(!paired){status=429;data={error:'配对失败'};}else data={ok:true};}
 else if(!paired){status=401;data={error:'需要配对'};}
 else if(request.method()==='POST'&&request.headers()['x-chrona-csrf']!=='test-csrf'){status=403;data={error:'CSRF'};}
 else if(url.pathname==='/api/session')data={csrf:'test-csrf',zone:'Asia/Shanghai',palette:{background:'#f4f6f8',surface:'#ffffff',text:'#202c36',muted:'#70808e',primary:'#486a85',outline:'#d7e0e7'},calendarAllowed:true,syncStatus:'模拟数据 · 同步状态'};
 else if(url.pathname==='/api/home')data={revision,items:candidates,courses:[{title:'高等数学',location:'东一 101',start:1791082800000,end:1791086400000,term:selected}],calendar:[],calendarState:'模拟数据 · 系统日历需在手机授权',date:'2026-10-04',review:1,failed:0};
 else if(url.pathname==='/api/inbox')data={revision,items:tasks,total:tasks.length,page:0,pageSize:12};
 else if(url.pathname==='/api/schedule')data={revision,items:candidates,total:candidates.length,page:0,pageSize:24};
 else if(url.pathname==='/api/task')data={revision,task:tasks.find(item=>item.id===Number(url.searchParams.get('id'))),candidates:candidates.filter(item=>item.taskId===Number(url.searchParams.get('id'))),images:[],files:[{id:7,name:'课程资料.pdf',size:2000}]};
 else if(url.pathname==='/api/timetable'&&request.method()==='GET')data={revision,terms:[{id:'2026-autumn',name:'2026 秋冬 · 浙江大学本科课表'}],selected,date:url.searchParams.get('date'),items:Array.from({length:9},(_,i)=>{const date=new Date(url.searchParams.get('date')+'T12:00:00');date.setDate(date.getDate()-(date.getDay()+6)%7+3+i%3);const day=date.toISOString().slice(0,10);return{title:['微积分（甲）Ⅰ','C程序设计基础','数字音视频基础与制作'][i%3],location:'紫金港东1A-301 · 浙江大学紫金港校区',description:'模拟课程',start:day+'T'+['08:00','13:25','16:15'][Math.floor(i/3)]+':00',end:day+'T'+['09:35','15:50','17:50'][Math.floor(i/3)]+':00',allDay:false};})};
 else if(request.method()==='POST'){mutations.push({path:url.pathname,body});revision++;
  if(url.pathname==='/api/task/create'){const id=nextId++;tasks.unshift({id,text:body.text,linkText:'',status:'ready',error:'',created:Date.now(),source:'模拟浏览器'});data={id,revision};}
  else if(url.pathname==='/api/task/edit'){tasks.find(item=>item.id===Number(body.id)).text=body.text;data={ok:true,revision};}
  else if(url.pathname.startsWith('/api/candidate/')){if(url.pathname.endsWith('/create'))candidates.push({...body,id:12,taskId:Number(body.id),calendarLinked:false});else if(url.pathname.endsWith('/delete'))candidates=candidates.filter(item=>item.id!==Number(body.candidateId));else Object.assign(candidates.find(item=>item.id===Number(body.candidateId)),body,{id:Number(body.candidateId)});data={ok:true,revision};}
  else if(url.pathname==='/api/task/delete'){const i=tasks.findIndex(item=>item.id===Number(body.id));tasks.splice(i,1);candidates=candidates.filter(item=>item.taskId!==Number(body.id));data={ok:true,revision};}
  else if(url.pathname==='/api/logout'){paired=false;data={ok:true};}
  else if(url.pathname==='/api/timetable'){if(body.action==='select')selected=body.term;data=body.action==='preview'?{replaced:[],revision}:{ok:true,revision};}
  else data={ok:true,revision};
 }else{status=404;data={error:'mock route missing'};}
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
}
async function checkReadingPalette(page){const values=await page.evaluate(()=>{const style=getComputedStyle(document.body),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');function rgb(value){ctx.clearRect(0,0,1,1);ctx.fillStyle=value;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3);}function luminance(c){return c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);}const surface=rgb(style.getPropertyValue('--surface')),background=rgb(style.backgroundColor);return {neutral:Math.max(...background)-Math.min(...background),ratios:['--text','--muted'].map(key=>{const a=luminance(rgb(style.getPropertyValue(key))),b=luminance(surface);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);})};});assert(values.neutral<=12,'neutral reading background');assert(values.ratios.every(value=>value>=4.5),'body and secondary text contrast >=4.5');}
(async()=>{await new Promise(resolve=>source.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',error=>errors.push(String(error)));await page.route('**/api/**',mock);await page.goto(`http://127.0.0.1:${source.address().port}`);await page.locator('#pair-form').waitFor();assert(await page.locator('#workspace').isHidden());await page.locator('#pair-code').fill('12');assert.equal(await page.evaluate(()=>document.querySelector('#pair-code').checkValidity()),false,'short numeric code rejected');await page.locator('#pair-code').fill('000007');await page.getByRole('button',{name:'连接手机',exact:true}).click();await page.getByRole('heading',{name:'今日安排'}).waitFor();await page.screenshot({path:path.join(out,'desktop-home.png'),fullPage:true});
 await page.locator('[data-page="schedule"]').click();await page.getByRole('heading',{name:'图书馆学习'}).waitFor();await page.locator('.result-list button').first().click();await page.getByRole('heading',{name:'记录详情'}).waitFor();assert(await page.locator('.raw-text').first().textContent().then(text=>text.includes('<script>unsafe()</script>')));assert.equal(await page.evaluate(()=>document.querySelectorAll('script').length),1,'untrusted raw content is text');
 await page.getByRole('button',{name:'修改原文',exact:true}).click();await page.locator('#field-text').fill('浏览器修改原文');await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByText('浏览器修改原文',{exact:true}).waitFor();assert(mutations.some(item=>item.path==='/api/task/edit'&&item.body.text==='浏览器修改原文'));
 await page.getByRole('button',{name:'修改日程',exact:true}).click();await page.locator('#field-title').fill('浏览器修改标题');await page.locator('#field-start').fill('2026-10-04T15:00');await page.locator('#field-end').fill('2026-10-04T16:00');await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('heading',{name:'浏览器修改标题'}).waitFor();const saved=mutations.find(item=>item.path==='/api/candidate/save').body;assert.equal(saved.start,Date.parse('2026-10-04T07:00:00Z'),'phone timezone rather than computer zone');
 await page.locator('#capture').click();await page.locator('#field-text').fill('手工日程原文');await page.getByRole('checkbox',{name:'交给手机 AI 整理为日程'}).uncheck();await page.getByRole('button',{name:'保存记录',exact:true}).click();await page.getByRole('button',{name:'手动建立日程'}).waitFor();await page.getByRole('button',{name:'手动建立日程'}).click();await page.getByRole('checkbox',{name:'全天（结束日期为下一天）'}).check();await page.locator('#field-start').fill('2026-10-05');await page.locator('#field-end').fill('2026-10-06');await page.getByRole('checkbox',{name:'仍需确认',exact:true}).uncheck();await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'修改日程'}).waitFor();const allDay=mutations.find(item=>item.path==='/api/candidate/create').body;assert.equal(allDay.start,Date.parse('2026-10-05T00:00:00Z'));assert.equal(allDay.end,Date.parse('2026-10-06T00:00:00Z'));
 await page.locator('[data-page="timetable"]').click();await page.getByRole('button',{name:'导入 ICS',exact:true}).waitFor();await checkReadingPalette(page);await page.screenshot({path:path.join(out,'desktop-light-timetable.png'),fullPage:true});assert(await page.evaluate(()=>document.querySelector('.timetable-filters select').getBoundingClientRect().width>=300),'readable semester selector');await page.getByRole('button',{name:'导入 ICS',exact:true}).click();await page.locator('#field-file').setInputFiles({name:'test.ics',mimeType:'text/calendar',buffer:Buffer.from('BEGIN:VCALENDAR\r\nEND:VCALENDAR')});await page.locator('#dialog').getByRole('button',{name:'导入',exact:true}).click();await page.locator('#dialog').waitFor({state:'hidden'});assert(mutations.some(item=>item.path==='/api/timetable'&&item.body.action==='import'));
 await page.locator('[data-page="inbox"]').click();await page.getByRole('heading',{name:'收件箱',exact:true}).waitFor();await page.locator('#theme').click();assert(await page.evaluate(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.fillStyle=getComputedStyle(document.querySelector('.result-list .card')).backgroundColor;ctx.fillRect(0,0,1,1);return ctx.getImageData(0,0,1,1).data[0]<100;}),'dark card background');await page.screenshot({path:path.join(out,'desktop-dark-inbox.png'),fullPage:true});await page.locator('[data-page="timetable"]').click();await page.getByRole('heading',{name:'课表',exact:true}).waitFor();await checkReadingPalette(page);await page.screenshot({path:path.join(out,'desktop-dark-timetable.png'),fullPage:true});await page.locator('[data-page="inbox"]').click();await page.getByRole('heading',{name:'收件箱',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile-inbox.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow');await page.locator('[data-page="timetable"]').click();await page.getByRole('heading',{name:'课表',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'timetable overflow stays inside wrapper');await page.screenshot({path:path.join(out,'mobile-timetable.png'),fullPage:true});
 await page.locator('#settings').click();await page.getByRole('button',{name:'断开当前浏览器'}).click();await page.locator('#pair-form').waitFor();assert(await page.locator('#workspace').isHidden());assert.equal(errors.length,0,errors.join('\n'));const result={type:'mock phone API; browser interaction only',checks:['pairing','home/schedule/inbox/timetable','raw-text XSS','raw-text edit','candidate edit','phone timezone','UTC all-day','manual capture','ICS import','logout','mobile overflow','dark theme','six-digit leading-zero pairing','neutral reading surfaces','text contrast >=4.5','readable semester selector'],mutations:mutations.map(item=>item.path),pageErrors:errors};fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await browser.close();source.close();}})().catch(error=>{console.error(error);source.close();process.exitCode=1;});
