from pathlib import Path
import os,subprocess
root=Path(__file__).resolve().parents[1];out=root/'build/lan-qr-check';out.mkdir(exist_ok=True)
files={
'android/view/View.java':'package android.view;public class View {public static final int GONE=8,VISIBLE=0;public int visibility;public Object tag;public void setVisibility(int v){visibility=v;}public void setTag(Object t){tag=t;}public Object getTag(){return tag;}}',
'android/graphics/Bitmap.java':'package android.graphics;public class Bitmap {public enum Config {ARGB_8888}public int w,h;public int[] pixels;public static Bitmap createBitmap(int w,int h,Config c){Bitmap b=new Bitmap();b.w=w;b.h=h;b.pixels=new int[w*h];return b;}public void setPixel(int x,int y,int c){pixels[y*w+x]=c;}}',
'android/widget/ImageView.java':'package android.widget;public class ImageView extends android.view.View {public android.graphics.Bitmap bitmap;public void setImageBitmap(android.graphics.Bitmap b){bitmap=b;}public void setImageDrawable(Object d){bitmap=null;}}',
'com/donglan/chrona/LanQrCheck.java':'''package com.donglan.chrona;import com.google.zxing.*;import com.google.zxing.common.*;public class LanQrCheck {public static void main(String[]a)throws Exception{android.widget.ImageView view=new android.widget.ImageView();LanAddressQr.update(view,"");check(view.visibility==8&&view.bitmap==null&&view.tag==null,"off hidden");for(String url:new String[]{"http://192.168.1.7:8765","http://10.0.0.9:8765"}){LanAddressQr.update(view,url);check(view.visibility==0&&url.equals(view.tag),"enabled/changed URL");android.graphics.Bitmap b=view.bitmap;String payload=new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(b.w,b.h,b.pixels)))).getText();check(payload.equals(url)&&!payload.contains("?"),"decoded URL only");for(int x=0;x<b.w;x++)check(b.pixels[x]==0xffffffff,"white quiet zone");LanAddressQr.update(view,url);check(view.bitmap==b,"unchanged no rerender");}LanAddressQr.update(view,"");check(view.visibility==8&&view.bitmap==null&&view.tag==null,"stop removes QR/payload");System.out.println("LAN QR: actual production encode/update decoded two URLs, 4-module quiet zone, enable/change/stop and cache passed");}static void check(boolean b,String s){if(!b)throw new AssertionError(s);}}'''}
for name,text in files.items():p=out/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text,encoding='utf-8')
jar=next((Path(os.environ.get('GRADLE_USER_HOME','F:/Android/GradleCache'))/'caches/modules-2/files-2.1/com.google.zxing/core/3.5.3').rglob('*.jar'));java=Path(os.environ.get('JAVA_HOME','D:/Minecraft/java21'))/'bin'
subprocess.run([str(java/'javac.exe'),'--release','17','-encoding','UTF-8','-cp',str(jar),'-d',str(out),str(root/'app/src/main/java/com/donglan/chrona/LanAddressQr.java'),*map(str,(out/x for x in files))],check=True)
subprocess.run([str(java/'java.exe'),'-cp',str(out)+os.pathsep+str(jar),'com.donglan.chrona.LanQrCheck'],check=True)
