/* Browser interaction check against clearly labelled mock phone data. No Android claims. */
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert');
const {chromium}=require('./lan_browser_cdp.cjs');
const root=path.resolve(__dirname,'../app/src/main/assets/lan'),out=path.resolve(__dirname,'../build/lan-web-checks');
fs.mkdirSync(out,{recursive:true});
const source=http.createServer((req,res)=>{const file={'/':'index.html','/app.js':'app.js','/style.css':'style.css'}[new URL(req.url,'http://localhost').pathname];if(!file){res.writeHead(404);res.end();return;}res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' blob:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path.join(root,file)));});
let paired=false,revision=1,nextId=2,activePage=null,pairingAvailable=true,validPairing="000007",pairRequests=0;
const tasks=[{id:1,text:'明天下午三点图书馆学习\n<script>unsafe()</script>',linkText:'链接正文 <b>保持原文</b>',status:'needs_review',error:'',created:1791072000000,source:'浏览器检查 · 模拟手机数据'}];
const candidate={id:11,taskId:1,title:'图书馆学习',start:1791072000000,end:1791075600000,zone:'Asia/Shanghai',location:'图书馆',description:'核对日程',category:'event',allDay:false,reminder:10,needsConfirmation:true,calendarLinked:false};
let candidates=[candidate],selected='2026-autumn';
const mutations=[],errors=[];
async function mock(route){const request=route.request(),url=new URL(request.url()),body=request.postDataJSON();let status=200,data={};
 if(url.pathname==='/api/pair'){pairRequests++;assert.equal(request.method(),'POST');assert(!request.url().includes('#pair='));if(activePage)assert.equal(await activePage.evaluate(()=>location.hash),'','fragment cleared before authentication');paired=pairingAvailable&&body.code===validPairing;if(!paired){status=429;data={error:'配对失败'};}else data={ok:true};}
 else if(!paired){status=401;data={error:'需要配对'};}
 else if(request.method()==='POST'&&request.headers()['x-chrona-csrf']!=='test-csrf'){status=403;data={error:'CSRF'};}
 else if(url.pathname==='/api/session')data={csrf:'test-csrf',zone:'Asia/Shanghai',palette:{background:'#f4f6f8',surface:'#ffffff',text:'#202c36',muted:'#70808e',primary:'#486a85',outline:'#d7e0e7'},calendarAllowed:true,syncStatus:'模拟数据 · 同步状态'};
 else if(url.pathname==='/api/home')data={revision,items:candidates,courses:[{title:'高等数学',location:'东一 101',start:1791082800000,end:1791086400000,term:selected}],calendar:[],calendarState:'模拟数据 · 系统日历需在手机授权',date:'2026-10-04',review:1,failed:0};
 else if(url.pathname==='/api/inbox')data={revision,items:tasks,total:tasks.length,page:0,pageSize:12};
 else if(url.pathname==='/api/schedule')data={revision,items:candidates,total:candidates.length,page:0,pageSize:24};
 else if(url.pathname==='/api/task')data={revision,task:tasks.find(item=>item.id===Number(url.searchParams.get('id'))),candidates:candidates.filter(item=>item.taskId===Number(url.searchParams.get('id'))),images:[],files:[{id:7,name:'课程资料.pdf',size:2000}]};
 else if(url.pathname==='/api/timetable'&&request.method()==='GET')data={revision,terms:[{id:'2026-autumn',name:'26–27 秋冬 · 秋学期'}],selected,date:url.searchParams.get('date'),items:Array.from({length:9},(_,i)=>{const date=new Date(url.searchParams.get('date')+'T12:00:00');date.setDate(date.getDate()-(date.getDay()+6)%7+3+i%3);const day=date.toISOString().slice(0,10);return{title:['微积分（甲）Ⅰ','C程序设计基础','数字音视频基础与制作'][i%3],location:'紫金港东1A-301 · 浙江大学紫金港校区',description:'模拟课程',start:day+'T'+['08:00','13:25','16:15'][Math.floor(i/3)]+':00',end:day+'T'+['09:35','15:50','17:50'][Math.floor(i/3)]+':00',allDay:false};})};
 else if(request.method()==='POST'){mutations.push({path:url.pathname,body});revision++;
  if(url.pathname==='/api/task/create'){const id=nextId++;tasks.unshift({id,text:body.text,linkText:'',status:'ready',error:'',created:Date.now(),source:'模拟浏览器'});data={id,revision};}
  else if(url.pathname==='/api/task/edit'){tasks.find(item=>item.id===Number(body.id)).text=body.text;data={ok:true,revision};}
  else if(url.pathname.startsWith('/api/candidate/')){if(url.pathname.endsWith('/create'))candidates.push({...body,id:12,taskId:Number(body.id),calendarLinked:false});else if(url.pathname.endsWith('/delete'))candidates=candidates.filter(item=>item.id!==Number(body.candidateId));else Object.assign(candidates.find(item=>item.id===Number(body.candidateId)),body,{id:Number(body.candidateId)});data={ok:true,revision};}
  else if(url.pathname==='/api/task/delete'){const i=tasks.findIndex(item=>item.id===Number(body.id));tasks.splice(i,1);candidates=candidates.filter(item=>item.taskId!==Number(body.id));data={ok:true,revision};}
  else if(url.pathname==='/api/logout'){paired=false;data={ok:true};}
  else if(url.pathname==='/api/timetable'){if(body.action==='select')selected=body.term;data=body.action==='preview'?{replaced:[],revision}:{ok:true,revision};}
  else data={ok:true,revision};
 }else{status=404;data={error:'mock route missing'};}
 await route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
}
async function screenshotIcons(page,name){const rect=await page.evaluate(()=>{const box=document.querySelector('.top-actions').getBoundingClientRect();return{x:box.x,y:box.y,width:box.width,height:box.height,scale:2};});const result=await page.cdp.send('Page.captureScreenshot',{format:'png',clip:rect});fs.writeFileSync(path.join(out,name),Buffer.from(result.data,'base64'));}
async function checkReadingPalette(page){const values=await page.evaluate(()=>{const style=getComputedStyle(document.body),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');function rgb(value){ctx.clearRect(0,0,1,1);ctx.fillStyle=value;ctx.fillRect(0,0,1,1);return [...ctx.getImageData(0,0,1,1).data].slice(0,3);}function luminance(c){return c.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);}const surface=rgb(style.getPropertyValue('--surface')),background=rgb(style.backgroundColor);return {neutral:Math.max(...background)-Math.min(...background),ratios:['--text','--muted'].map(key=>{const a=luminance(rgb(style.getPropertyValue(key))),b=luminance(surface);return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);})};});assert(values.neutral<=12,'neutral reading background');assert(values.ratios.every(value=>value>=4.5),'body and secondary text contrast >=4.5');}
async function checkModalSelect(page){
 await page.setViewportSize({width:390,height:500});
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 await page.locator('#dialog .select-trigger').click();
 const geometry=await page.evaluate(()=>{const menu=document.querySelector('.select-menu'),r=menu.getBoundingClientRect();return{top:r.top,bottom:r.bottom,left:r.left,right:r.right,open:menu.matches(':popover-open'),animation:menu.getAnimations().length,dialog:menu.closest('dialog')?.open};});
 assert(geometry.open&&geometry.dialog&&geometry.top>=0&&geometry.bottom<=500&&geometry.left>=0&&geometry.right<=390,'mobile modal popover not clipped');
 await page.evaluate(()=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true})));
 const expected=await page.evaluate(()=>{const text=document.activeElement.textContent;return [...document.querySelector('#field-category').options].find(option=>option.textContent===text).value;});
 await page.cdp.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await page.cdp.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});
 assert.equal(await page.locator('#field-category').evaluate(element=>element.value),expected,'Enter changes actual native form value');
 assert(await page.evaluate(()=>document.activeElement.classList.contains('select-trigger')),'Enter returns focus');
 await page.locator('#dialog .select-trigger').click();await page.screenshot({path:path.join(out,'dropdown-mobile-modal.png')});
 await page.cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true});const touch=await page.evaluate(()=>{const r=document.querySelector('.select-menu [aria-selected=true]').getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};});await page.cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch]});await page.cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>document.querySelector('#dialog .select-trigger').getAttribute('aria-expanded')),'false','touch selects and dismisses');await page.cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await page.locator('#dialog .select-trigger').click();
 await page.evaluate(()=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));assert(await page.locator('#dialog').evaluate(element=>element.open),'menu Escape does not dismiss editor');
 await page.setViewportSize({width:1280,height:900});
}
(async()=>{await new Promise(resolve=>source.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{const page=await browser.newPage({viewport:{width:1280,height:900}});page.on('pageerror',error=>errors.push(String(error)));await page.route('**/api/**',mock);activePage=page;const base=`http://127.0.0.1:${source.address().port}/`;let before=pairRequests;
 await page.goto(base+'?case=scan#pair=000007');await page.getByRole('heading',{name:'今日安排'}).waitFor();assert.equal(pairRequests,before+1,'leading-zero scan pairs once');assert.equal(await page.evaluate(()=>location.hash),'');assert.equal(await page.locator('#pair-code').evaluate(element=>element.value),'','scanned code never copied into form');
 paired=false;await page.evaluate(()=>api('/api/session').catch(()=>{}));await page.locator('#pair-form').waitFor();assert.equal(pairRequests,before+1,'expired session does not retry scanned code');
 await page.goto(base+'?case=refresh');await page.locator('#pair-form').waitFor();assert.equal(pairRequests,before+1,'clean refresh cannot reuse scan code');
 before=pairRequests;await page.goto(base+'?case=bad#pair=999999');await page.locator('#toast').waitFor();assert(await page.locator('#workspace').isHidden());assert.equal(pairRequests,before+1,'wrong scan pairs only once');assert.equal(await page.evaluate(()=>location.hash),'');
 before=pairRequests;pairingAvailable=false;await page.goto(base+'?case=expired#pair=000007');await page.locator('#toast').waitFor();assert.equal(pairRequests,before+1,'expired code falls back once');assert(await page.locator('#workspace').isHidden());pairingAvailable=true;
 before=pairRequests;await page.goto(base+'?case=malformed#pair=12x');await page.locator('#toast').waitFor();assert.equal(pairRequests,before,'malformed fragment never posted');assert.equal(await page.evaluate(()=>location.hash),'');
 validPairing='000009';before=pairRequests;await page.goto(base+'?case=rotated#pair=000009');await page.getByRole('heading',{name:'今日安排'}).waitFor();assert.equal(pairRequests,before+1,'rotated QR connects');validPairing='000007';paired=false;
 await page.goto(`http://127.0.0.1:${source.address().port}`);await page.locator('#pair-form').waitFor();assert(await page.locator('#workspace').isHidden());await page.locator('#pair-code').fill('12');assert.equal(await page.evaluate(()=>document.querySelector('#pair-code').checkValidity()),false,'short numeric code rejected');await page.locator('#pair-code').fill('000007');await page.getByRole('button',{name:'连接手机',exact:true}).click();await page.getByRole('heading',{name:'今日安排'}).waitFor();await page.screenshot({path:path.join(out,'desktop-home.png'),fullPage:true});await screenshotIcons(page,'settings-icons-light.png');

 await page.evaluate(async()=>{await navigate('inbox');await Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{})));});
 for(const dark of [false,true]){
  await page.evaluate(dark=>document.body.classList.toggle('dark',dark),dark);
  await page.locator('.select-trigger').click();
  assert(await page.evaluate(()=>document.querySelector('.select-menu').matches(':popover-open')),'custom list is in top layer');
  await page.screenshot({path:path.join(out,'dropdown-'+(dark?'dark':'light')+'.png')});
  await page.evaluate(()=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true})));
  assert(await page.evaluate(()=>document.activeElement.getAttribute('role')==='option'),'arrow focuses option');
  await page.evaluate(()=>document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));
  assert(await page.evaluate(()=>document.activeElement.classList.contains('select-trigger')&&document.activeElement.getAttribute('aria-expanded')==='false'),'escape restores trigger focus');
 }
 await page.evaluate(()=>{document.body.classList.remove('dark');document.querySelector('.select-trigger').click();});
 await page.evaluate(()=>document.querySelector('.select-menu button').click());
 await page.evaluate(async()=>{await new Promise(r=>setTimeout(r,220));});
 assert.equal(await page.evaluate(()=>document.querySelector('select').value),'','native value/change preserved');
 await page.locator('.select-trigger').click();const outside=await page.locator('h1').evaluate(element=>{const r=element.getBoundingClientRect();return{x:r.x+10,y:r.y+10};});await page.cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...outside});await page.cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...outside});
 assert.equal(await page.evaluate(()=>document.querySelector('.select-trigger').getAttribute('aria-expanded')),'false','outside click closes');
 const plus=await page.evaluate(()=>{const button=document.querySelector('#capture').getBoundingClientRect(),svg=document.querySelector('#capture svg').getBoundingClientRect(),bounds=document.querySelector('#capture svg').getBBox();return {dx:svg.x+svg.width/2-button.x-button.width/2,dy:svg.y+svg.height/2-button.y-button.height/2,bx:bounds.x+bounds.width/2,by:bounds.y+bounds.height/2};});
 assert(Math.abs(plus.dx)<.01&&Math.abs(plus.dy)<.01&&plus.bx===12&&plus.by===12,'actual plus strokes centered');console.log('PLUS '+JSON.stringify(plus));
 await page.evaluate(async()=>{await navigate('home');});
 const navMotion=await page.evaluate(async()=>{await navigate('schedule');return document.querySelector('#content').getAnimations().map(animation=>animation.effect.getTiming().duration);});assert.deepEqual(navMotion,[180],'route enter motion starts');
 await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});
 assert.equal(await page.evaluate(async()=>{await render();return document.querySelector('#content').getAnimations().length;}),0,'routine render does not replay motion');
 await page.evaluate(async()=>{await Promise.all([navigate('schedule'),navigate('inbox'),navigate('home')]);await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});assert(await page.getByRole('heading',{name:'今日安排'}).isHidden()===false,'latest rapid route wins');
 const iconGeometry=await page.evaluate(()=>{const gear=document.querySelector('#settings svg'),theme=document.querySelector('#theme svg'),bounds=gear.getBBox();return{gear:gear.getBoundingClientRect().width,theme:theme.getBoundingClientRect().width,x:bounds.x+bounds.width/2,y:bounds.y+bounds.height/2,stroke:getComputedStyle(gear).strokeWidth};});assert.equal(iconGeometry.gear,iconGeometry.theme);assert(Math.abs(iconGeometry.x-12)<.1&&Math.abs(iconGeometry.y-12)<.1,'centered standard gear');assert.equal(iconGeometry.stroke,'2px');
 assert(await page.evaluate(async()=>{capture();const input=document.querySelector('#field-text');input.value='动画输入保留';input.focus();await render();return input.value==='动画输入保留'&&document.activeElement===input&&document.querySelector('#dialog').getAnimations().length===1;}),'dialog entry retains draft/focus during data render');
 assert(await page.evaluate(()=>{closeDialog();return document.querySelector('#dialog').open&&document.querySelector('#dialog').inert;}),'dialog exit starts without blocking action');
 await page.evaluate(async()=>{showDialog('快速重开',body=>body.append(document.createTextNode('模拟')));await Promise.all(document.querySelector('#dialog').getAnimations().map(animation=>animation.finished.catch(()=>{})));});assert(await page.locator('#dialog').evaluate(element=>element.open&&!element.inert),'stale close cannot dismiss reopened dialog');
 await page.evaluate(async()=>{closeDialog();await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});assert(await page.locator('#dialog').isHidden());
 await page.evaluate(async()=>{await navigate('task/1');await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});
 assert(await page.evaluate(()=>{const details=document.querySelector('details');details.querySelector('summary').click();return details.open&&details.lastElementChild.getAnimations().length===1;}),'disclosure open motion');
 await page.evaluate(async()=>{await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));document.querySelector('summary').click();await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});assert(await page.evaluate(()=>!document.querySelector('details').open),'disclosure close ends collapsed');
 await page.evaluate(async()=>{const summary=document.querySelector('summary');summary.click();summary.click();summary.click();await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});assert(await page.evaluate(()=>document.querySelector('details').open),'rapid disclosure ends in last requested state');
 await page.cdp.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 assert(await page.evaluate(async()=>{await navigate('inbox');capture();const zero=document.getAnimations().length===0&&getComputedStyle(document.querySelector('#capture')).transitionDuration==='0s';closeDialog();return zero&&!document.querySelector('#dialog').open;}),'reduced motion suppresses route/modal/button animations');
 await page.cdp.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'no-preference'}]});await page.evaluate(async()=>{await navigate('home');await Promise.all(document.getAnimations().map(animation=>animation.finished.catch(()=>{})));});

 await page.locator('[data-page="schedule"]').click();await page.getByRole('heading',{name:'图书馆学习'}).waitFor();await page.locator('.result-list button').first().click();await page.getByRole('heading',{name:'记录详情'}).waitFor();assert(await page.locator('.raw-text').first().textContent().then(text=>text.includes('<script>unsafe()</script>')));assert.equal(await page.evaluate(()=>document.querySelectorAll('script').length),1,'untrusted raw content is text');
 await page.getByRole('button',{name:'修改原文',exact:true}).click();await page.locator('#field-text').fill('浏览器修改原文');await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByText('浏览器修改原文',{exact:true}).waitFor();assert(mutations.some(item=>item.path==='/api/task/edit'&&item.body.text==='浏览器修改原文'));
 await page.getByRole('button',{name:'修改日程',exact:true}).click();await checkModalSelect(page);await page.locator('#field-title').fill('浏览器修改标题');await page.locator('#field-start').fill('2026-10-04T15:00');await page.locator('#field-end').fill('2026-10-04T16:00');await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('heading',{name:'浏览器修改标题'}).waitFor();const saved=mutations.find(item=>item.path==='/api/candidate/save').body;assert.equal(saved.start,Date.parse('2026-10-04T07:00:00Z'),'phone timezone rather than computer zone');
 await page.locator('#capture').click();await page.locator('#field-text').fill('手工日程原文');await page.getByRole('checkbox',{name:'交给手机 AI 整理为日程'}).uncheck();await page.getByRole('button',{name:'保存记录',exact:true}).click();await page.getByRole('button',{name:'手动建立日程'}).waitFor();await page.getByRole('button',{name:'手动建立日程'}).click();await page.getByRole('checkbox',{name:'全天（结束日期为下一天）'}).check();await page.locator('#field-start').fill('2026-10-05');await page.locator('#field-end').fill('2026-10-06');await page.getByRole('checkbox',{name:'仍需确认',exact:true}).uncheck();await page.locator('#dialog').getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'修改日程'}).waitFor();const allDay=mutations.find(item=>item.path==='/api/candidate/create').body;assert.equal(allDay.start,Date.parse('2026-10-05T00:00:00Z'));assert.equal(allDay.end,Date.parse('2026-10-06T00:00:00Z'));
 await page.locator('[data-page="timetable"]').click();await page.getByRole('button',{name:'导入 ICS',exact:true}).waitFor();await checkReadingPalette(page);await page.screenshot({path:path.join(out,'desktop-light-timetable.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.querySelector('.timetable-filters select')),null,'automatic term has no selector');await page.getByRole('button',{name:'导入 ICS',exact:true}).click();await page.locator('#field-file').setInputFiles({name:'test.ics',mimeType:'text/calendar',buffer:Buffer.from('BEGIN:VCALENDAR\r\nEND:VCALENDAR')});await page.locator('#dialog').getByRole('button',{name:'导入',exact:true}).click();await page.locator('#dialog').waitFor({state:'hidden'});assert(mutations.some(item=>item.path==='/api/timetable'&&item.body.action==='import'));
 await page.locator('[data-page="inbox"]').click();await page.getByRole('heading',{name:'收件箱',exact:true}).waitFor();await page.locator('#theme').click();assert(await page.evaluate(()=>{const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');ctx.fillStyle=getComputedStyle(document.querySelector('.result-list .card')).backgroundColor;ctx.fillRect(0,0,1,1);return ctx.getImageData(0,0,1,1).data[0]<100;}),'dark card background');await page.screenshot({path:path.join(out,'desktop-dark-inbox.png'),fullPage:true});await screenshotIcons(page,'settings-icons-dark.png');await page.locator('[data-page="timetable"]').click();await page.getByRole('heading',{name:'26–27 秋冬 · 秋学期',exact:true}).waitFor();await checkReadingPalette(page);await page.screenshot({path:path.join(out,'desktop-dark-timetable.png'),fullPage:true});await page.locator('[data-page="inbox"]').click();await page.getByRole('heading',{name:'收件箱',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(out,'mobile-inbox.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile overflow');await page.locator('[data-page="timetable"]').click();await page.getByRole('heading',{name:'26–27 秋冬 · 秋学期',exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'timetable overflow stays inside wrapper');await page.screenshot({path:path.join(out,'mobile-timetable.png'),fullPage:true});
 await page.locator('#settings').click();await page.getByRole('button',{name:'断开当前浏览器'}).click();await page.locator('#pair-form').waitFor();assert(await page.locator('#workspace').isHidden());assert.equal(errors.length,0,errors.join('\n'));const result={type:'mock phone API; browser interaction only',checks:['pairing','home/schedule/inbox/timetable','raw-text XSS','raw-text edit','candidate edit','phone timezone','UTC all-day','manual capture','ICS import','logout','mobile overflow','dark theme','six-digit leading-zero pairing','neutral reading surfaces','text contrast >=4.5','automatic term without selector','themed top-layer dropdown','keyboard Escape and arrows','native select value/change','outside dropdown dismiss','centered plus glyph','QR automatic pairing','QR URL cleanup before POST','QR failure and expiry fallback','QR no automatic retry or reuse','QR rotation and malformed input','standard centered Lucide gear','navigation motion and no refresh replay','rapid route cancellation','modal entry exit and reopen','draft focus preservation','disclosure open close and rapid toggles','prefers-reduced-motion'],mutations:mutations.map(item=>item.path),pageErrors:errors};fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}finally{await browser.close();source.close();}})().catch(error=>{console.error(error);source.close();process.exitCode=1;});
