import com.donglan.chrona.ai.SemanticEventNormalizer;
import com.donglan.chrona.data.CandidateRules;
import com.donglan.chrona.data.EventCandidate;
import org.json.JSONObject;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;

/** Offline checks; run with a desktop org.json implementation rather than android.jar stubs. */
public final class SemanticEventNormalizerCheck {
    private static final long NOW = Instant.parse("2026-09-28T02:00:00Z").toEpochMilli();
    private static int checks;

    public static void main(String[] args) throws Exception {
        EventCandidate task = parse(base("task").put("start", time(null, "11:00", 1)));
        check(task.startAtMillis == at("2026-09-29T03:00:00Z"), "relative local date");
        check(task.endAtMillis - task.startAtMillis == 30 * 60_000L, "task default duration");
        check(!task.needsConfirmation, "complete relative time");
        check(task.endAutoGenerated, "default end has explicit provenance");
        EventCandidate relativeInterval = parse(base("event")
                .put("start", new JSONObject().put("offset_minutes", 60))
                .put("end", new JSONObject().put("offset_minutes", 90)));
        check(relativeInterval.startAtMillis == NOW + 60 * 60_000L
                && relativeInterval.endAtMillis == NOW + 90 * 60_000L
                && !relativeInterval.needsConfirmation, "relative end uses instant rather than inherited date");
        for (String category : new String[]{"event", "reminder", "note"}) {
            EventCandidate item = parse(base(category).put("start", time("2026-09-29", "11:00", null)));
            long expected = category.equals("event") ? 60 : category.equals("reminder") ? 5 : 15;
            check(item.endAtMillis - item.startAtMillis == expected * 60_000L, category + " duration");
        }
        EventCandidate explicit = parse(base("event").put("start", time("2026-09-29", "11:00", null))
                .put("duration_minutes", 90));
        check(explicit.endAtMillis - explicit.startAtMillis == 90 * 60_000L, "explicit duration");
        check(!explicit.endAutoGenerated, "AI duration is protected");
        EventCandidate durationMismatch = parse(base("event").put("start", time("2026-09-29", "11:00", null))
                .put("end", time("2026-09-29", "12:00", null)).put("duration_minutes", 90));
        check(durationMismatch.needsConfirmation && durationMismatch.endAtMillis - durationMismatch.startAtMillis == 60 * 60_000L,
                "explicit end survives contradictory duration");
        check(!durationMismatch.endAutoGenerated, "AI end is protected");
        check(parse(base("event").put("start", time("2026-09-29", "11:00", null))
                .put("duration_minutes", 0)).endAtMillis == null, "invalid duration has no default interval");
        EventCandidate leapDay = parse(base("event").put("start", time("2028-02-29", "11:00", null)));
        check(leapDay.startAtMillis == at("2028-02-29T03:00:00Z"), "valid leap date");
        check(parse(base("event").put("start", time("2026-02-30", "11:00", null))).startAtMillis == null,
                "invalid calendar date");
        EventCandidate missing = parse(base("event").put("start", time(null, "11:00", null)));
        check(missing.startAtMillis == null && missing.needsConfirmation, "clock without date stays unresolved");
        EventCandidate dateOnly = parse(base("event").put("start", time("2026-09-29", null, null)));
        check(dateOnly.startAtMillis == null && dateOnly.needsConfirmation, "date without clock stays unresolved");
        EventCandidate contradictory = parse(base("task").put("start", time("2026-09-30", "11:00", 1)));
        check(contradictory.startAtMillis == at("2026-09-30T03:00:00Z") && contradictory.needsConfirmation,
                "explicit date has priority but contradiction requires confirmation");
        JSONObject monday = time(null, "11:00", null).put("weekday", 1).put("week_offset", 1);
        check(parse(base("event").put("start", monday)).startAtMillis == at("2026-10-05T03:00:00Z"), "next week weekday");
        JSONObject passedMonday = time(null, "09:00", null).put("weekday", 1);
        check(parse(base("event").put("start", passedMonday)).startAtMillis == at("2026-10-05T01:00:00Z"),
                "next weekday after elapsed clock");
        JSONObject offset = new JSONObject().put("offset_minutes", 20);
        check(parse(base("reminder").put("start", offset)).startAtMillis == NOW + 20 * 60_000L, "instant offset");
        EventCandidate sameDateEnd = parse(base("event").put("start", time("2026-09-29", "11:00", null))
                .put("end", time(null, "12:00", null)));
        check(sameDateEnd.endAtMillis == at("2026-09-29T04:00:00Z"), "end inherits start date");
        EventCandidate negative = parse(base("event").put("start", time("2026-09-28", "23:00", null))
                .put("end", time(null, "01:00", null)));
        check(negative.endAtMillis == null && negative.needsConfirmation, "negative interval never guesses overnight");
        EventCandidate overnight = parse(base("event").put("start", time("2026-09-28", "23:00", null))
                .put("end", time(null, "01:00", 1)));
        check(overnight.endAtMillis - overnight.startAtMillis == 2 * 60 * 60_000L, "explicit overnight day offset");
        EventCandidate allDay = parse(base("event").put("all_day", true)
                .put("start", time("2026-09-29", null, null)).put("end", time("2026-09-30", null, null)));
        check(allDay.startAtMillis == at("2026-09-29T00:00:00Z")
                && allDay.endAtMillis == at("2026-10-01T00:00:00Z") && "UTC".equals(allDay.timeZoneId),
                "inclusive all-day dates become exclusive UTC boundary");
        EventCandidate due = parse(base("task").put("due", time("2026-09-28", "10:30", null)));
        check("deadline".equals(due.category) && due.endAtMillis - due.startAtMillis == 60_000L, "due maps deadline");
        check(due.reminderMinutesBefore == 10 && due.title.contains("2026-09-28 10:30"), "urgent deadline reminder and title");
        check(parse(base("deadline").put("due", time("2026-09-28", "20:00", null))).reminderMinutesBefore == 30,
                "same-day deadline reminder");
        check(parse(base("deadline").put("due", time("2026-09-30", "10:00", null))).reminderMinutesBefore == 120,
                "near deadline reminder");
        check(parse(base("deadline").put("due", time("2026-10-10", "10:00", null))).reminderMinutesBefore == 360,
                "distant deadline reminder");
        JSONObject noReminder = base("deadline").put("due", time("2026-09-28", "10:30", null))
                .put("reminder_specified", true).put("reminder_minutes_before", JSONObject.NULL);
        check(parse(noReminder).reminderMinutesBefore == null, "explicit no reminder");
        check(parse(noReminder.put("reminder_minutes_before", 0)).reminderMinutesBefore == 0, "explicit zero reminder");
        EventCandidate legacy = parse(base("task").put("start_at_millis", NOW).put("end_at_millis", JSONObject.NULL));
        check(legacy.startAtMillis == NOW && legacy.endAtMillis == NOW + 30 * 60_000L, "legacy millis protocol");
        EventCandidate invalidZone = parse(base("task").put("time_zone_id", "Mars/Olympus")
                .put("start_at_millis", NOW));
        check(invalidZone.startAtMillis == null && invalidZone.needsConfirmation, "invalid timezone");
        check(parse(base("event").put("start_at_millis", Long.MAX_VALUE)).startAtMillis == null, "epoch range");
        check(parse(base("event").put("start", time("2026-09-29", "11:00", null))
                .put("duration_minutes", Long.MAX_VALUE)).endAtMillis == null, "duration overflow");
        for (String[] dst : new String[][]{{"2026-03-08", "02:30"}, {"2026-11-01", "01:30"}}) {
            EventCandidate ambiguous = parse(base("event").put("time_zone_id", "America/New_York")
                    .put("start", time(dst[0], dst[1], null)));
            check(ambiguous.startAtMillis == null && ambiguous.needsConfirmation, "DST gap or overlap");
        }
        check(CandidateRules.apply(Arrays.asList(task, task)).size() == 1, "identical draft deduplicated");
        EventCandidate differentLocation = copy(task, "另一地点", task.reminderMinutesBefore, task.category);
        check(CandidateRules.apply(Arrays.asList(task, differentLocation)).size() == 2, "location difference preserved");
        EventCandidate differentReminder = copy(task, task.location, 15, task.category);
        check(CandidateRules.apply(Arrays.asList(task, differentReminder)).size() == 2, "reminder difference preserved");
        List<EventCandidate> simultaneousTasks = CandidateRules.apply(Arrays.asList(task, differentLocation));
        check(!simultaneousTasks.get(0).needsConfirmation && !simultaneousTasks.get(1).needsConfirmation,
                "simultaneous tasks are not merged or marked as appointment conflict");
        List<EventCandidate> appointments = CandidateRules.apply(Arrays.asList(copy(task, "A", null, "event"),
                copy(task, "B", null, "event")));
        check(appointments.size() == 2 && appointments.get(0).needsConfirmation && appointments.get(1).needsConfirmation,
                "appointment overlap retained and marked");
        System.out.println("SemanticEventNormalizerCheck passed: " + checks + " checks");
    }

    private static JSONObject base(String category) throws Exception {
        return new JSONObject().put("title", "事项").put("category", category).put("needs_confirmation", false)
                .put("time_zone_id", JSONObject.NULL).put("all_day", false);
    }

    private static JSONObject time(String date, String clock, Integer day) throws Exception {
        return new JSONObject().put("date", date == null ? JSONObject.NULL : date)
                .put("time", clock == null ? JSONObject.NULL : clock).put("day_offset", day == null ? JSONObject.NULL : day);
    }

    private static EventCandidate parse(JSONObject object) throws Exception {
        return SemanticEventNormalizer.fromJson(7, object, NOW, "Asia/Shanghai");
    }

    private static EventCandidate copy(EventCandidate value, String location, Integer reminder, String category) {
        return new EventCandidate(0, value.taskId, value.title, value.startAtMillis, value.endAtMillis,
                value.timeZoneId, location, value.description, reminder, false, null, category, value.allDay);
    }

    private static long at(String instant) { return Instant.parse(instant).toEpochMilli(); }
    private static void check(boolean value, String label) {
        checks++;
        if (!value) throw new AssertionError(label);
    }
}
